hanghae99-final-project/front_end

- .eslintrc.js
- src/service-worker.js
> fix: 개행 문제

- src/components/setTimeModal/SetTimeModal.jsx
- src/components/setTimeModal/SetTimePicker.jsx
- src/components/setTimeModal/SetWatchModal.jsx
- src/components/setTimeModal/TimePicker.jsx
> fix: crlf 오류 문제

- src/components/TimeTimer.jsx
- src/css/mainPage.module.css
- src/css/timeTimer.module.css
- src/pages/Home.jsx
> fix : 랭킹 바텀시트 뼈대 구성

- src/css/ranking.module.css
- src/pages/Ranking.jsx
> fix : 랭킹 최상단 메세지관련 기능 수정

- src/components/common/Footer.jsx
> fix : 홈화면 푸터와 바텀시트 z-index 조정

- src/components/TimeTimer.jsx
- src/pages/Ranking.jsx
> fix: 머지 오류

- src/css/ranking.module.css
> fix : 랭킹페이지 css  수정

- src/components/weeklyGraph/WeeklyDataGraph.jsx
- 주간 공부 그래프 월 이동 시 올바르게 동작하지 않는 이슈 해결
<br>
@shkiimaa @H4nHS
> fix: 주간 공부 그래프 월 이동 시 올바르게 동작하지 않는 이슈 해결 #33

- src/components/join/Nickname.jsx
- src/pages/ModifyProfile.jsx
- src/pages/Ranking.jsx
- src/pages/css/profile.module.css
- src/pages/css/rankingPage.module.css
-
<br>
-
<br>
@shkiimaa @Jong1co
> fix : 프로필수정 기능구현 완료 , 회원가입-닉네임 부분 애니메이션 추가 및 기능구현 완료

- src/app/slice/toDoSlice.jsx
- src/app/store.jsx
- src/components/dDay/MainDday.jsx
- src/components/modal/SetTimeModal.jsx
- src/components/modal/SetWatchModal.jsx
- src/components/modal/setTimeModal.module.css
- src/components/stopwatch/Stopwatch.jsx
- src/components/stopwatch/stopwatch.module.css
- src/components/studying/studing.module.css
- src/components/timeTimer/StopButton.jsx
- src/components/timeTimer/TimeTimer.jsx
- src/components/timeTimer/timeTimer.module.css
- src/components/todo/ToDoList.jsx
- src/components/todo/ToDoModify.jsx
- src/components/todo/ToDoPost.jsx
- src/components/todo/TodoBtn.jsx
- src/index.css
- src/layout/Layout.jsx
- src/pages/MainPage.jsx
- src/pages/Ranking.jsx
- src/pages/css/mainPage.module.css
- d-day 비어있을 때 클릭 시 작성 페이지로 이동
- modal 양쪽 padding 조절 및 title 수정
- stopwatch 완료 시 종료 모달
- studing online표시 블러처리
- timeTimer 목표설정 아이콘 안 보이는 버그 수정
<br>
> design: design: Dday, modal, stopwatch, studing, timeTimer, index.css, layout, mainPage 수정

- src/app/slice/DdaySlice.jsx
- src/components/dDay/DdayList.jsx
- src/components/dDay/DdayModify.jsx
- src/components/dDay/MainDday.jsx
- src/components/dDay/ddayModify.module.css
- src/components/todo/ToDoList.jsx
- src/pages/Ranking.jsx
- feature: D-day 기능 구현 완료
<br>
@Jong1co @H4nHS
> feature: D-day 기능 구현 완료

- src/app/slice/DdaySlice.jsx
- src/components/dDay/MainDday.jsx
- src/components/footer/Footer.jsx
- src/components/modal/setTimeModal.module.css
- src/components/stopwatch/Stopwatch.jsx
- src/components/weeklyGraph/WeeklyDataGraph.jsx
- src/components/weeklyGraph/weeklyDataGraph.module.css
- src/pages/MyPage.jsx
- src/pages/Ranking.jsx
- footer: 배경화면 색상 변경 및 mypage에서 작게 나오는 오류 수정
- d-day: d-day가 없을 시 에러가 발생하여 화면이 렌더링 되지 않는 이슈 해결
<br>
> fix: d-day 오류 해결 및 footer 수정

- src/app/slice/calenderSlice.jsx
- src/components/calender/Calender.jsx
- src/components/todo/ToDoList.jsx
- src/components/todo/toDoList.module.css
- src/pages/MyPage.jsx
- src/pages/ToDo.jsx
- src/pages/css/toDoPage.module.css
- design: todolist css 수정
<br>
@Jong1co  @H4nHS
> design: todolist css 수정

- .eslintrc
- .prettierrc
- package.json
- public/index.html
- src/app/slice/calenderSlice.jsx
- src/app/slice/toDoSlice.jsx
- src/components/calender/Calender.jsx
- src/components/profile/ProfileTodoList.jsx
- src/components/stopwatch/Stopwatch.jsx
- src/components/timeTimer/TimeTimer.jsx
- src/components/todo/ToDoList.jsx
- src/components/todo/toDoList.module.css
- src/layout/Layout.jsx
- src/pages/KakaoFinish.jsx
- src/pages/LoginPage.jsx
- src/pages/ToDo.jsx
- src/pages/css/loginPage.module.css
- src/pages/css/toDoPage.module.css
- loding bar 및 라이브러리 추가
- prettier, eslint 추가
<br>
> chore: loding bar 및 라이브러리 추가 및 prettier, eslint 추가

- src/app/slice/DdaySlice.jsx
- src/app/slice/calenderSlice.jsx
- src/components/todo/ToDoList.jsx
- src/components/todo/ToDoModify.jsx
- src/components/todo/ToDoPost.jsx
- src/components/todo/toDoList.module.css
- src/components/todo/toDoPost.module.css
- src/utils/changeTimeForm.js
- src/utils/changeTimeSimpleForm.js
- todoList 반응형 css 추가 및 todo list 깨지는 현상 수정
- utils 함수 react fragment 제거
<br>
@shkiimaa
> design: todoList 반응형 css 추가, utils함수 fragment 제거

- src/app/slice/toDoSlice.jsx
- src/components/calender/Calender.jsx
- src/components/profile/ProfileTodoList.jsx
- src/components/todo/ToDoList.jsx
- fix: mypage todolist 데이터 못 불러오는 버그 수정
<br>
@H4nHS  @Jong1co
> fix: mypage todolist 데이터  못 불러오는 버그 수정

- src/components/surveyModal/SurveyModal.jsx
- src/components/surveyModal/surveyModal.module.css
> chore: 폴더 오타 수정 및 설문조사 페이지 연결

- src/app/slice/mySlice.jsx
- src/app/slice/toDoSlice.jsx
- src/components/surveyModal/SurveyModal.jsx
- src/components/surveyModal/surveyModal.module.css
- src/components/weeklyGraph/WeeklyDataGraph.jsx
- todo post를 하면 에러가 나면서 망가지는 현상 수정
<br>
> fix: todo slice 오류 수정

- package.json
- src/components/infoModal/infoModal.module.css
- src/components/modal/SetWatchModal.jsx
- src/components/modal/setTimeModal.module.css
- src/components/weeklyGraph/WeeklyDataGraph.jsx
- src/pages/LoginPage.jsx
- src/pages/ModifyProfile.jsx
- src/pages/css/loginPage.module.css
- src/pages/css/profile.module.css
> design: font 적용 및 색상 조정

- src/components/join/Nickname.jsx
- src/pages/Join.jsx
- src/pages/KakaoFinish.jsx
- src/pages/ModifyProfile.jsx
> fix : 회원가입,프로필수정 유효성검사 메세지 수정 로그인시 토큰 로컬스토리지 저장관련 문제해결 가입자 회원가입페이지 접근제한

- package.json
- src/components/dDay/DdayList.jsx
- src/components/dDay/ddayList.module.css
- src/pages/KakaoFinish.jsx
> design: d-day css 수정

- src/components/dDay/DdayList.jsx
- src/components/dDay/ddayList.module.css
- src/components/join/Age.jsx
- src/components/join/join.module.css
- src/components/modal/setTimeModal.module.css
- src/components/modal/timePickerBox.module.css
- src/components/timeTimer/TimeTimer.jsx
- src/components/timeTimer/timeTimer.module.css
> design: d-day 클릭 시 애니메이션 적용

- src/components/dDay/DdayList.jsx
- src/components/dDay/PostDday.jsx
- src/components/dDay/ddayList.module.css
- src/components/dDay/postDday.module.css
- src/pages/DdayPage.jsx
- src/pages/css/DdayPage.module.css
- D-day 캘린더 오늘날짜, 선택날짜 표시CSS 수정
- 버튼 CSS 수정
<br>
@Jong1co
> design: D-day 캘린더 오늘날짜, 선택날짜 표시CSS 수정 / 버튼 CSS 수정

- src/components/dDay/DdayList.jsx
- src/components/dDay/PostDday.jsx
- src/components/surveyModal/SurveyModal.jsx
- src/pages/DdayPage.jsx
- d-day: 추가, 수정하기 클릭 시 모달창 닫히게 수정
<br>
> fix: 추가, 수정하기 클릭 시 모달창 닫히게 수정

- src/components/dDay/PostDday.jsx
- src/components/todo/ToDoPost.jsx
- src/shared/Router.jsx
- d-day, todolist input max-length 20자로 수정
<br>
@Jong1co @H4nHS
> docs: d-day, todolist input max-length 20자로 수정

- src/components/weeklyGraph/WeeklyDataGraph.jsx
- weekly data가 전송되지 않던 오류 수정
<br>
> fix: weekly data가 전송되지 않던 오류 수정

- src/app/slice/toDoSlice.jsx
- src/components/dDay/MainDday.jsx
- src/components/dDay/PostDday.jsx
- src/components/dDay/mainDday.module.css
- src/components/footer/Footer.jsx
- src/components/footer/footer.module.css
- src/components/infoModal/InfoModal.jsx
- src/components/modal/SetTimeModal.jsx
- src/components/modal/SetWatchModal.jsx
- src/components/quote/Quote.jsx
- src/components/stopwatch/Stopwatch.jsx
- src/components/stopwatch/stopwatch.module.css
- src/components/studying/Studying.jsx
- src/components/studying/studing.module.css
- src/components/surveyModal/SurveyModal.jsx
- src/components/timeTimer/StopButton.jsx
- src/components/timeTimer/TimeTimer.jsx
- src/components/timeTimer/timeTimer.module.css
- src/components/weeklyGraph/WeeklyDataGraph.jsx
- src/layout/Layout.jsx
- src/pages/LoginPage.jsx
- src/pages/MainPage.jsx
- src/pages/css/loginPage.module.css
- src/pages/css/mainPage.module.css
- src/pages/mainPage/ButtonBox.jsx
- src/pages/mainPage/CircleTimer.jsx
- src/pages/mainPage/Gradient.jsx
- src/pages/mainPage/Styled.jsx
- src/pages/mainPage/Timer.jsx
- loginPage : 로그인 버튼이 짤리는 현상 수정
- d-day : 하나가 아닌 모든 d-day를 슬라이드로 보여주도록 개선
- studying : 유저가 의도를 파악하지 못하는 현상이 발생하여 직관적으로 UI 수정
- weekly data : 컨벤션 불일치로 인해 시간의 색상이 잘못 표기되는 오류 수정
- stopwatch : 타이머 종료 후 blur 클릭 시 타이머가 끝나지 않던 오류 수정
<br>
> 유저 피드백을 통한 오류 및 UI /UX 개선

- public/firebase-messaging-sw.js
- src/App.js
- src/components/totalStudyTime/MyPageStudyTime.jsx
- FCM mac 또는 iphone 접속 시 아무 것도 안 뜨는 오류 테스트 ( 맥에서)
<br>
> fix: FCM mac 또는 iphone 접속 시 아무 것도 안 뜨는 오류 테스트

- package.json
- public/firebase-messaging-sw.js
- src/App.js
- src/app/slice/profileSlice.jsx
- src/components/calender/Calender.jsx
- src/components/dDay/DdayList.jsx
- src/components/dDay/PostDday.jsx
- src/components/profile/ProfileTodoList.jsx
- src/components/totalStudyTime/MyPageStudyTime.jsx
- src/pages/Ranking.jsx
- src/pages/Ranking/RankingBox.jsx
- src/pages/css/mypage.module.css
- src/pages/css/rankingPage.module.css
- src/pages/myPage/ContentsBox.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/contentsBox.module.css
- src/shared/Router.jsx
- fix: D-day 시간 안 맞는 버그 수정
- chore: 프로필 투두리스트 날짜 변경 후 캘린더 월 변경시 매월 1일로 선택되게 추가
- docs: console.log 삭제
<br>
@Jong1co  @H4nHS
> merge: D-day 시간 안 맞는 버그 수정, 프로필 투두리스트 날짜 변경 후 캘린더 월 변경시 매월 1일로 선택되게 추가

- src/pages/css/rankingPage.module.css
> chore : 랭킹페이지 래킹컨테이너 1,2,3 등 반응형 적용

- src/components/calender/Calender.jsx
- src/components/dDay/PostDday.jsx
- refactor: Date함수 -> dayjs로 변경, 캘린더 로직 수정
- chore: 변동없는 변수 let -> const로 변경
<br>
@Jong1co  @H4nHS
> refactor: Date함수 -> dayjs로 변경, 캘린더 로직 수정  @shkiimaa
